enum ALIGNMENTS {
	NATURAL,
	MECHANICAL,
	ASTRAL,
	HEIGHT
}

enum SPRITES {
	HACHACHACHA,
	DIIPSY,
	GLIDRAKE,
	PODRIC,
	SPARMATE,
	CRUSTULAR,
	FISTICOGS,
	BOOKISH,
	PLEEP,
	FISHMONGER,
	GEMBO,
	JOE,
	MIRREFRACT,
	FLOOPWALKER,
	SONGBIRD,
	SHREDATOR,
	FURVOR,
	GASTRONIMO,
	DURENDOUX,
	STAGEFRITE,
	FLAMILIAR,
	SCROOTINEYES,
	ARRAYNGE,
	TICKDOFF,
	FORTUGA,
	SPYOTIS,
	DRUMLINE,
	REVOLTURE,
	CLEANSAGE,
	FLOTSU,
	HEATSUNE,
	BLITZKRANE,
	EXONOLITH,
	PUGILOON,
	MRSUDSY,
	DEMOLITOPS,
	DOORMAUS,
	ZEPHIRA,
	CANUKI,
	JACKHAMMER,
	SPLASHGUARD,
	UPROOTER,
	SNUGBUG,
	PUNKLOPS,
	PLASMASS,
	OBSIDUAL,
	NINTOX,
	CHROMALIODON,
	CRAGMA,
	CORVOLT,
	WYRMPOOL,
	VEWRR,
	DECIDRUID,
	CENOTOMB,
	STEWARDRAKE,
	HECKID,
	DOMINO,
	ANACHRONAUT,
	SHPUPO,
	NEEDLEPAW,
	OMNOST,
	PRISMATTER,
	KRONARC,
	COSMALCOS,
	HEIGHT
}

enum SPRITE_PARAMS {
	ID,
	NAME,
	SPRITE,
	ABILITY,
	ALIGNMENT,
	SPELL_LIST,
	POWER,
	RESISTANCE,
	FIRE,
	WATER,
	STORM,
	EARTH,
	AGILITY,
	LUCK,
	SIZE,
	HEIGHT
}

enum SPRITE_SIZES {
	X_SMALL,
	SMALL,
	MEDIUM,
	LARGE,
	X_LARGE,
	HEIGHT
}

enum SPRITE_POSES {
	IDLE,
	ATTACK,
	SPELL,
	HURT,
	HEIGHT
}

#region	CREATE ALL SPELL LISTS

	#region		DIIPSY
		var diipsySpells = ds_list_create();
		
		ds_list_add(diipsySpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.HOLY_WATER,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.TYPHOON,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.WATERLOG,
			SPELLS.UNDERTOW,
			SPELLS.EMPATHIZE,
			SPELLS.DOWNPOUR,
			SPELLS.OSMOSIS,
			SPELLS.LANDSLIDE,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.ENDLESS_RIVER,
			SPELLS.CLOUD_BREAK,
			SPELLS.HAIL_SPHERA
		);
		
	#endregion
	
	#region		SPYOTIS
		var spyotisSpells = ds_list_create();
		
		ds_list_add(spyotisSpells,
			SPELLS.EXPEL_FORCE,
			SPELLS.TYPHOON,
			SPELLS.AIR_PRESSURE,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.EMPATHIZE,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.DARK_DEAL
		);
		
	#endregion
	
	#region		NEW SPRITE 1
		var flamiliarSpells = ds_list_create();
		
		ds_list_add(flamiliarSpells,
			SPELLS.FIREBALL,
			SPELLS.HEALING_LIGHT,
			SPELLS.LOOMING_DANGER,
			SPELLS.EMPATHIZE,
			SPELLS.HELLFIRE,
			SPELLS.PYROKINESIS,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.PURIFYING_FLAME,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.BURN_OUT,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.FULL_THRUST,
			SPELLS.DARK_DEAL
		);
		
	#endregion
	
	#region		NEW SPRITE 2
		var snugbugSpells = ds_list_create();
				
		ds_list_add(snugbugSpells,
			SPELLS.DECAY,
			SPELLS.HEALING_LIGHT,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.SUPERBLOOM,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.EMPATHIZE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.STINKBOMB
		);
				
	#endregion
	
	#region		NEW SPRITE 3
		var vewrrSpells = ds_list_create();
				
		ds_list_add(vewrrSpells,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.WATERLOG,
			SPELLS.SUPERBLOOM,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.UNDERTOW,
			SPELLS.HELLFIRE,
			SPELLS.BALL_LIGHTNING,
			SPELLS.QUICKSAND,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.DOWNPOUR,
			SPELLS.ARC_BLAST,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.FLASH_FREEZE,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.WIND_SLICE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.LAVA_SPIRE,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST,
			SPELLS.SPHERAS_DEMISE,
			SPELLS.ERADICATE,
			SPELLS.DARK_DEAL
		);
					
	#endregion
	
	#region		NEW SPRITE 4
		var decidruidSpells = ds_list_create();
						
		ds_list_add(decidruidSpells,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HEALING_LIGHT,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.SUPERBLOOM,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.LANDSLIDE,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.TREMOR,
			SPELLS.PURIFYING_FLAME,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.SPHERAS_DEMISE,
			SPELLS.HAIL_SPHERA
		);
								
	#endregion
	
	#region		NEW SPRITE 5
		var heckidSpells = ds_list_create();
						
		ds_list_add(heckidSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.NEBULA_STORM,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.TYPHOON,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.AIR_PRESSURE,
			SPELLS.SUPERBLOOM,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.HELLFIRE,
			SPELLS.QUICKSAND,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.LANDSLIDE,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.SKYDIVE,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.REARRANGE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.DARK_DEAL,
			SPELLS.HAIL_SPHERA
		);
							
	#endregion

	#region		SPARMATE
		var sparmateSpells = ds_list_create();
		
		ds_list_add(sparmateSpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.UNDERTOW,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_PARRY,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.ENDLESS_RIVER,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST
		);
			
	#endregion
	
	#region		FISTICOGS
		var fisticogsSpells = ds_list_create();
		
		ds_list_add(fisticogsSpells,
			SPELLS.SHOCK,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.RAPID_STRIKE,
			SPELLS.ARC_BLAST,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.BURN_OUT,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST,
			SPELLS.BROADCAST_DATA
		);
		
	#endregion
	
	#region		CRUSTULAR
		var crustularSpells	= ds_list_create();
		
		ds_list_add(crustularSpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.EXPEL_FORCE,
			SPELLS.TYPHOON,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.UNDERTOW,
			SPELLS.QUICKSAND,
			SPELLS.DOWNPOUR,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.ENDLESS_RIVER,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST
		);
		
	#endregion
	
	#region		OBSIDUAL
		var obsidualSpells = ds_list_create();
		
		ds_list_add(obsidualSpells,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.FIREBALL,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.EMPATHIZE,
			SPELLS.HELLFIRE,
			SPELLS.QUICKSAND,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.PURIFYING_FLAME,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DIONS_PARRY,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.BURN_OUT,
			SPELLS.WIND_SLICE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.LAVA_SPIRE,
			SPELLS.VOLCANIC_ERUPTION
		);
		
	#endregion
	
	#region		STAGEFRITE
		var stagefriteSpells = ds_list_create();
		
		ds_list_add(stagefriteSpells,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.HEALING_LIGHT,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.WATERLOG,
			SPELLS.SUPERBLOOM,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.EMPATHIZE,
			SPELLS.HELLFIRE,
			SPELLS.QUICKSAND,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.DOWNPOUR,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.STINKBOMB,
			SPELLS.SPHERAS_CURSE,
			SPELLS.COLLAPSE_SPACE,
			SPELLS.SPHERAS_DEMISE
		);
		
	#endregion
	
	#region		REVOLTURE
		var revoltureSpells = ds_list_create();
		
		ds_list_add(revoltureSpells,
			SPELLS.FIREBALL,
			SPELLS.HOLY_WATER,
			SPELLS.DECAY,
			SPELLS.TYPHOON,
			SPELLS.WATERLOG,
			SPELLS.AIR_PRESSURE,
			SPELLS.SUPERBLOOM,
			SPELLS.LOOMING_DANGER,
			SPELLS.STEAM_BATH,
			SPELLS.HELLFIRE,
			SPELLS.QUICKSAND,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.OSMOSIS,
			SPELLS.PURIFYING_FLAME,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.WIND_SLICE,
			SPELLS.SPHERAS_CURSE
		);
		
	#endregion
	
	#region		PUGILOON
		var pugiloonSpells = ds_list_create();
		
		ds_list_add(pugiloonSpells,
			SPELLS.EXPEL_FORCE,
			SPELLS.TYPHOON,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.AIR_PRESSURE,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.EMPATHIZE,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.SKYDIVE,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.PURIFYING_FLAME,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_PARRY,
			SPELLS.WIND_SLICE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST
		);
		
	#endregion
	
	#region		SPLASHGUARD
		var splashguardSpells = ds_list_create();
		
		ds_list_add(splashguardSpells,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.TYPHOON,
			SPELLS.WATERLOG,
			SPELLS.AIR_PRESSURE,
			SPELLS.SUPERBLOOM,
			SPELLS.STEAM_BATH,
			SPELLS.EMPATHIZE,
			SPELLS.QUICKSAND,
			SPELLS.DOWNPOUR,
			SPELLS.OSMOSIS,
			SPELLS.LANDSLIDE,
			SPELLS.STINKBOMB
		);
	#endregion
	
	#region		DEMOLITOPS
		var demolitopsSpells = ds_list_create();
		
		ds_list_add(demolitopsSpells,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.FIREBALL,
			SPELLS.BALL_LIGHTNING,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.LAVA_SPIRE,
			SPELLS.KNOCK_OVER,
			SPELLS.VOLCANIC_ERUPTION
		);
		
	#endregion
	
	#region		UPROOTER
		var uprooterSpells = ds_list_create();
		
		ds_list_add(uprooterSpells,
			SPELLS.DECAY,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.WATERLOG,
			SPELLS.SUPERBLOOM,
			SPELLS.INTERCEPT,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.SPHERAS_CURSE,
			SPELLS.BROADCAST_DATA,
			SPELLS.SPHERAS_DEMISE
		);
		
	#endregion
	
	#region		NINTOX
		var nintoxSpells = ds_list_create();
		
		ds_list_add(nintoxSpells,
			SPELLS.FIREBALL,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.STEAM_BATH,
			SPELLS.HELLFIRE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.PURIFYING_FLAME,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DIONS_PARRY,
			SPELLS.BURN_OUT,
			SPELLS.WIND_SLICE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.FULL_THRUST,
			SPELLS.BROADCAST_DATA
		);
	#endregion
	
	#region		SHPUPO
		var shpupoSpells = ds_list_create();
		
		ds_list_add(shpupoSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.NEBULA_STORM,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.PYROKINESIS,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD
		);
		
	#endregion

	#region		GEMBO
		var gemboSpells = ds_list_create();
		
		ds_list_add(gemboSpells,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.EMPATHIZE,
			SPELLS.ARC_BLAST,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.FULL_THRUST
		);
	#endregion
	
	#region		HACHA-CHACHA
		var hachaSpells = ds_list_create();
		
		ds_list_add(hachaSpells,
			SPELLS.FIREBALL,
			SPELLS.EMPATHIZE,
			SPELLS.PYROKINESIS,
			SPELLS.PURIFYING_FLAME,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.BURN_OUT,
			SPELLS.LAVA_SPIRE
		);
	#endregion

	#region		PODRIC
		var podricSpells = ds_list_create();
		
		ds_list_add(podricSpells,
			SPELLS.DECAY,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.RAPID_STRIKE,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DIONS_PARRY,
			SPELLS.WIND_SLICE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST
		);
	#endregion
	
	#region		NEEDLEPAW
		var needlepawSpells = ds_list_create();
		
		ds_list_add(needlepawSpells,
			SPELLS.SHOCK,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.TELEKINETIC_BLAST
		);
	#endregion
	
	#region		SUDSY
		var sudsySpells = ds_list_create();
		
		ds_list_add(sudsySpells,
			SPELLS.HOLY_WATER,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.WATERLOG,
			SPELLS.STEAM_BATH,
			SPELLS.EMPATHIZE,
			SPELLS.OSMOSIS,
			SPELLS.JABULS_FIGHT_SONG
		);
	#endregion
	
	#region		BOOKISH
		var bookishSpells = ds_list_create();
		
		ds_list_add(bookishSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.TIDAL_FORCE,
			SPELLS.NEBULA_STORM,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.TYPHOON,
			SPELLS.HEALING_LIGHT,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.INTERCEPT,
			SPELLS.EMPATHIZE,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.REARRANGE
		);
	#endregion
	
	#region		PLEEP
		var pleepSpells = ds_list_create();
		
		ds_list_add(pleepSpells,
			SPELLS.FIREBALL,
			SPELLS.EXPEL_FORCE,
			SPELLS.TYPHOON,
			SPELLS.AIR_PRESSURE,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.EMPATHIZE,
			SPELLS.HELLFIRE,
			SPELLS.PYROKINESIS,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.WIND_SLICE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK
		);
	#endregion
		
	#region		GLIDRAKE
		var glidrakeSpells = ds_list_create();
		
		ds_list_add(glidrakeSpells,
			SPELLS.NEBULA_STORM,
			SPELLS.FIREBALL,
			SPELLS.TYPHOON,
			SPELLS.AIR_PRESSURE,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.BALL_LIGHTNING,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.DIONS_PARRY,
			SPELLS.WIND_SLICE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.SKYDIVE,
			SPELLS.SHOCK,
			SPELLS.SPHERAS_CURSE,
			SPELLS.DARK_DEAL,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HAIL_SPHERA
		);
	#endregion
	
	#region		FURVOR
		var furvorSpells = ds_list_create();
		
		ds_list_add(furvorSpells,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.SUPERBLOOM,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.SNEAK_ATTACK,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST
		);
	#endregion	
	
	#region		ZEPHIRA
		var zephiraSpells = ds_list_create();

		ds_list_add(zephiraSpells,
			SPELLS.NEBULA_STORM,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.TYPHOON,
			SPELLS.HEALING_LIGHT,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.AIR_PRESSURE,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.SKYDIVE,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.REARRANGE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.SPHERAS_DEMISE
		);
	#endregion
	
	#region		FISHMONGER
		var fishmongerSpells = ds_list_create();
		
		ds_list_add(fishmongerSpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.EXPEL_FORCE,
			SPELLS.TYPHOON,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.WATERLOG,
			SPELLS.LOOMING_DANGER,
			SPELLS.UNDERTOW,
			SPELLS.DOWNPOUR,
			SPELLS.FLASH_FREEZE,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_PARRY,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.ENDLESS_RIVER,
			SPELLS.CLOUD_BREAK,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST,
		);
	#endregion
	
	#region		SONGBIRD
		var songbirdSpells = ds_list_create();
		
		ds_list_add(songbirdSpells,
			SPELLS.EXPEL_FORCE,
			SPELLS.TYPHOON,
			SPELLS.HEALING_LIGHT,
			SPELLS.AIR_PRESSURE,
			SPELLS.SUPERBLOOM,
			SPELLS.EMPATHIZE,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.SKYDIVE,
			SPELLS.PURIFYING_FLAME,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.REARRANGE,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.BROADCAST_DATA
		);	
	#endregion
	
	#region		EXONOLITH
		var exonolithSpells = ds_list_create();
		
		ds_list_add(exonolithSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.SHOCK,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HEALING_LIGHT,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.LANDSLIDE,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.TREMOR,
			SPELLS.PURIFYING_FLAME,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.CLOUD_BREAK,
			SPELLS.TELEKINETIC_BLAST
		);
	#endregion
	
	#region		DRUMLINE
		var drumlineSpells = ds_list_create();
		
		ds_list_add(drumlineSpells,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.EMPATHIZE,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.REARRANGE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_GAMBLING_BLAST,
		);
	#endregion
	
	#region		MIRREFRACT
		var mirrefractSpells = ds_list_create();
		
		ds_list_add(mirrefractSpells,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.BALL_LIGHTNING,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_PARRY,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST
		);
	#endregion
	
	#region		FORTUGA
		var fortugaSpells = ds_list_create();
		
		ds_list_add(fortugaSpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.WATERLOG,
			SPELLS.INTERCEPT,
			SPELLS.UNDERTOW,
			SPELLS.EMPATHIZE,
			SPELLS.DOWNPOUR,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.ENDLESS_RIVER,
		);
	#endregion
	
	#region		TIKDOFF
		var tikdoffSpells = ds_list_create();
		
		ds_list_add(tikdoffSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.FIREBALL,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.HELLFIRE,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.BURN_OUT,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.LAVA_SPIRE,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST
		);
	#endregion
	
	#region		ARRAYNGE
		var arrayngeSpells = ds_list_create();
		
		ds_list_add(arrayngeSpells,
			SPELLS.SHOCK,
			SPELLS.EXPEL_FORCE,
			SPELLS.INTERCEPT,
			SPELLS.ARC_BLAST,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.REARRANGE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.BROADCAST_DATA,
			SPELLS.COLLAPSE_SPACE
		);
	#endregion
	
	#region		SCROOTINEYES
		var scrootineyesSpells = ds_list_create();
		
		ds_list_add(scrootineyesSpells,
			SPELLS.DECAY,
			SPELLS.TYPHOON,
			SPELLS.AIR_PRESSURE,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.EMPATHIZE,
			SPELLS.SKYDIVE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.WIND_SLICE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.BROADCAST_DATA
		);
	#endregion
	
	#region		JOE
		var joeSpells = ds_list_create();
		
		ds_list_add(joeSpells,
			SPELLS.FIREBALL,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.WATERLOG,
			SPELLS.INTERCEPT,
			SPELLS.STEAM_BATH,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.OSMOSIS,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.BURN_OUT,
			SPELLS.EXPAND_TIME
		);
	#endregion
	
	#region		CANUKI
		var canukiSpells = ds_list_create();
		
		ds_list_add(canukiSpells,
			SPELLS.DECAY,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.SKYDIVE,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.STINKBOMB,
			SPELLS.SPHERAS_DEMISE
		);
	#endregion
	
	#region		GASTRONIMO
		var gastronimoSpells = ds_list_create();
		
		ds_list_add(gastronimoSpells,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HEALING_LIGHT,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.STEAM_BATH,
			SPELLS.LANDSLIDE,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.TREMOR,
			SPELLS.PURIFYING_FLAME,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST
		);
	#endregion
	
	#region		FLOTSU
		var flotsuSpells = ds_list_create();
		
		ds_list_add(flotsuSpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.HOLY_WATER,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.TYPHOON,
			SPELLS.HEALING_LIGHT,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.WATERLOG,
			SPELLS.AIR_PRESSURE,
			SPELLS.INTERCEPT,
			SPELLS.STEAM_BATH,
			SPELLS.UNDERTOW,
			SPELLS.EMPATHIZE,
			SPELLS.DOWNPOUR,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.OSMOSIS,
			SPELLS.FLASH_FREEZE,
			SPELLS.LANDSLIDE,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.TREMOR,
			SPELLS.SKYDIVE,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.WIND_SLICE,
			SPELLS.ENDLESS_RIVER,
			SPELLS.TELEKINETIC_BLAST
		);
	#endregion
	
	#region		BLITZKRANE
		var blitzkraneSpells = ds_list_create();
		
		ds_list_add(blitzkraneSpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.NEBULA_STORM,
			SPELLS.HOLY_WATER,
			SPELLS.SHOCK,
			SPELLS.TYPHOON,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.WATERLOG,
			SPELLS.AIR_PRESSURE,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.UNDERTOW,
			SPELLS.BALL_LIGHTNING,
			SPELLS.DOWNPOUR,
			SPELLS.ARC_BLAST,
			SPELLS.SKYDIVE,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.WIND_SLICE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.FULL_THRUST,
			SPELLS.EXPAND_TIME,
			SPELLS.SPHERAS_DEMISE
		);
	#endregion
	
	#region		HEATSUNE
		var heatsuneSpells = ds_list_create();
		
		ds_list_add(heatsuneSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.NEBULA_STORM,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HEALING_LIGHT,
			SPELLS.RAPID_STRIKE,
			SPELLS.HELLFIRE,
			SPELLS.BALL_LIGHTNING,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.PURIFYING_FLAME,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.BURN_OUT,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.LAVA_SPIRE,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.COLLAPSE_SPACE,
			SPELLS.SPHERAS_DEMISE,
			SPELLS.VOLCANIC_ERUPTION
		);
			
	#endregion
	
	#region		FLOOPWALKER
		var floopwalkerSpells = ds_list_create();
		
		ds_list_add(floopwalkerSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.NEBULA_STORM,
			SPELLS.DECAY,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HEALING_LIGHT,
			SPELLS.TYPHOON,
			SPELLS.AIR_PRESSURE,
			SPELLS.SUPERBLOOM,
			SPELLS.RAPID_STRIKE,
			SPELLS.STEAM_BATH,
			SPELLS.BALL_LIGHTNING,
			SPELLS.ARC_BLAST,
			SPELLS.LANDSLIDE,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK,
			SPELLS.BROADCAST_DATA,
			SPELLS.EXPAND_TIME
		);
	#endregion
	
	#region		STEWARDRAKE
		var stewardrakeSpells = ds_list_create();
		
		ds_list_add(stewardrakeSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.NEBULA_STORM,
			SPELLS.HOLY_WATER,
			SPELLS.SHOCK,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.TYPHOON,
			SPELLS.HEALING_LIGHT,
			SPELLS.EMPATHIZE,
			SPELLS.PYROKINESIS,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.SKYDIVE,
			SPELLS.PURIFYING_FLAME,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.CLOUD_BREAK
		);
	#endregion
	
	#region		DOORMAUS
		var doormausSpells = ds_list_create();
		
		ds_list_add(doormausSpells,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HEALING_LIGHT,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.REARRANGE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.BROADCAST_DATA,
			SPELLS.COLLAPSE_SPACE,
		);
	#endregion
	
	#region		PLASMASS
		var plasmassSpells = ds_list_create();
		
		ds_list_add(plasmassSpells,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.EXPEL_FORCE,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.AIR_PRESSURE,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.BALL_LIGHTNING,
			SPELLS.ARC_BLAST,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.BURN_OUT,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST,
		);
	#endregion
	
	#region		SHREDATOR
		var shredatorSpells = ds_list_create();
		
		ds_list_add(shredatorSpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.TYPHOON,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.UNDERTOW,
			SPELLS.DOWNPOUR,
			SPELLS.SNEAK_ATTACK,
			SPELLS.ENDLESS_RIVER,
			SPELLS.FULL_THRUST
		);
	#endregion
	
	#region		JACKHAMMER
		var jackhammerSpells = ds_list_create();
		
		ds_list_add(jackhammerSpells,
			SPELLS.SHOCK,
			SPELLS.EXPEL_FORCE,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.HELLFIRE,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.FULL_THRUST,
			SPELLS.SPHERAS_DEMISE
		);
	#endregion
	
	#region		STINKLOPS
		var stinklopsSpells = ds_list_create();
		
		ds_list_add(stinklopsSpells,
			SPELLS.FIREBALL,
			SPELLS.DECAY,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.HELLFIRE,
			SPELLS.QUICKSAND,
			SPELLS.PYROKINESIS,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.STINKBOMB,
			SPELLS.SPHERAS_CURSE,
			SPELLS.CLOUD_BREAK,
			SPELLS.FULL_THRUST,
			SPELLS.KNOCK_OVER,
		);
	#endregion
	
	#region		DURENDOUX
		var durendouxSpells = ds_list_create();
		
		ds_list_add(durendouxSpells,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.HOLY_WATER,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HEALING_LIGHT,
			SPELLS.QUICKSAND,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE
		);
	#endregion
	
	#region		CENOTOMB
		var cenotombSpells = ds_list_create();
		
		ds_list_add(cenotombSpells,
			SPELLS.FIREBALL,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LOOMING_DANGER,
			SPELLS.HELLFIRE,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.FLASH_FREEZE,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.COLLAPSE_SPACE,
			SPELLS.EXPAND_TIME,
			SPELLS.SPHERAS_DEMISE
		);
	#endregion
	
	#region		CLEANSAGE
		var cleansageSpells = ds_list_create();
		
		ds_list_add(cleansageSpells,
			SPELLS.FIREBALL,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.TYPHOON,
			SPELLS.HEALING_LIGHT,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.AIR_PRESSURE,
			SPELLS.SUPERBLOOM,
			SPELLS.INTERCEPT,
			SPELLS.STEAM_BATH,
			SPELLS.EMPATHIZE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.PURIFYING_FLAME,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.BURN_OUT,
			SPELLS.STINKBOMB,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.EXPAND_TIME
		);
	#endregion
	
	#region		WYRMPOOL
		var wyrmpoolSpells = ds_list_create();
		
		ds_list_add(wyrmpoolSpells,
			SPELLS.TIDAL_FORCE,
			SPELLS.TYPHOON,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.WATERLOG,
			SPELLS.AIR_PRESSURE,
			SPELLS.UNDERTOW,
			SPELLS.DOWNPOUR,
			SPELLS.FLASH_FREEZE,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.ENDLESS_RIVER,
			SPELLS.CLOUD_BREAK
		);
	#endregion
	
	#region		CRAGMA
		var cragmaSpells = ds_list_create();
		
		ds_list_add(cragmaSpells,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.FIREBALL,
			SPELLS.HELLFIRE,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.BURN_OUT,
			SPELLS.STINKBOMB,
			SPELLS.LAVA_SPIRE,
			SPELLS.VOLCANIC_ERUPTION
		);
	#endregion
	
	#region		CORVOLT
		var corvoltSpells = ds_list_create();
		
		ds_list_add(corvoltSpells,
			SPELLS.NEBULA_STORM,
			SPELLS.SHOCK,
			SPELLS.TYPHOON,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.AIR_PRESSURE,
			SPELLS.BALL_LIGHTNING,
			SPELLS.DOWNPOUR,
			SPELLS.ARC_BLAST,
			SPELLS.SKYDIVE,
			SPELLS.WIND_SLICE,
			SPELLS.CLOUD_BREAK
		);
	#endregion
	
	#region		CHROMALIODON
		var chromaliodonSpells = ds_list_create();
		
		ds_list_add(chromaliodonSpells,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.LOOMING_DANGER,
			SPELLS.HELLFIRE,
			SPELLS.ARC_BLAST,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.BURN_OUT,
			SPELLS.LAVA_SPIRE,
			SPELLS.FULL_THRUST,
			SPELLS.KNOCK_OVER,
			SPELLS.VOLCANIC_ERUPTION
		);
	#endregion
	
	#region		DOMINO
		var dominoSpells = ds_list_create();
		
		ds_list_add(dominoSpells,
			SPELLS.FIREBALL,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.RAPID_STRIKE,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.HELLFIRE,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.PYROKINESIS,
			SPELLS.ARC_BLAST,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.JABULS_FIGHT_SONG,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.REARRANGE,
			SPELLS.SNEAK_ATTACK,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_PARRY,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.FULL_THRUST,
			SPELLS.BROADCAST_DATA,
			SPELLS.SPHERAS_DEMISE
		);
	#endregion
	
	#region		ANACHRONAUT
		var anachronautSpells = ds_list_create();
		
		ds_list_add(anachronautSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.TIDAL_FORCE,
			SPELLS.NEBULA_STORM,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.HEALING_LIGHT,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.ENDLESS_RIVER,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.BROADCAST_DATA,
			SPELLS.EXPAND_TIME,
			SPELLS.SPHERAS_DEMISE
		);
	#endregion
	
	#region		OMNOST
		var omnostSpells = ds_list_create();
		
		ds_list_add(omnostSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.TIDAL_FORCE,
			SPELLS.NEBULA_STORM,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.FIREBALL,
			SPELLS.HOLY_WATER,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LADY_SOLANUS_GRACE,
			SPELLS.TYPHOON,
			SPELLS.HEALING_LIGHT,
			SPELLS.RUBURS_WATER_CANNON,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.WATERLOG,
			SPELLS.AIR_PRESSURE,
			SPELLS.SUPERBLOOM,
			SPELLS.LOOMING_DANGER,
			SPELLS.STEAM_BATH,
			SPELLS.UNDERTOW,
			SPELLS.HELLFIRE,
			SPELLS.BALL_LIGHTNING,
			SPELLS.QUICKSAND,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.PYROKINESIS,
			SPELLS.DOWNPOUR,
			SPELLS.ARC_BLAST,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.OSMOSIS,
			SPELLS.FLASH_FREEZE,
			SPELLS.LANDSLIDE,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.SHIFT_PERSPECTIVE,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.TREMOR,
			SPELLS.PURIFYING_FLAME,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.REARRANGE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_GAMBLING_BLAST,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.BURN_OUT,
			SPELLS.STINKBOMB,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.LAVA_SPIRE,
			SPELLS.ENDLESS_RIVER,
			SPELLS.CLOUD_BREAK,
			SPELLS.BROADCAST_DATA,
			SPELLS.VOLCANIC_ERUPTION
		);
	#endregion
	
	#region		PRISMATTER
		var prismatterSpells = ds_list_create();
		
		ds_list_add(prismatterSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.TIDAL_FORCE,
			SPELLS.NEBULA_STORM,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.RUBURS_GRAPPLE,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.AIR_PRESSURE,
			SPELLS.SUPERBLOOM,
			SPELLS.RAPID_STRIKE,
			SPELLS.INTERCEPT,
			SPELLS.UNDERTOW,
			SPELLS.QUICKSAND,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.LANDSLIDE,
			SPELLS.TREMOR,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.CRECIAS_CRYSTAL_SPIKES,
			SPELLS.REARRANGE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_PARRY,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.BURN_OUT,
			SPELLS.WIND_SLICE,
			SPELLS.CRECIAS_CRYSTAL_WIND,
			SPELLS.LAVA_SPIRE,
			SPELLS.ENDLESS_RIVER,
			SPELLS.CLOUD_BREAK,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.KNOCK_OVER,
			SPELLS.FULL_THRUST,
			SPELLS.COLLAPSE_SPACE,
			SPELLS.VOLCANIC_ERUPTION
		);
	#endregion
	
	#region		KRONARC
		var kronarcSpells = ds_list_create();
		
		ds_list_add(kronarcSpells,
			SPELLS.SOLAR_FLARE,
			SPELLS.TIDAL_FORCE,
			SPELLS.NEBULA_STORM,
			SPELLS.TECTONIC_SHIFT,
			SPELLS.HOLY_WATER,
			SPELLS.SHOCK,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.LUSIAS_HARVEST_SPELL,
			SPELLS.SUPERBLOOM,
			SPELLS.LOOMING_DANGER,
			SPELLS.INTERCEPT,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.TREMOR,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.MAGNETIC_PULSE,
			SPELLS.WIND_SLICE,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.LAVA_SPIRE,
			SPELLS.ENDLESS_RIVER,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.EXPAND_TIME,
			SPELLS.SPHERAS_DEMISE,
			SPELLS.VOLCANIC_ERUPTION,
			SPELLS.TIME_LOOP,
			SPELLS.HAIL_SPHERA
		);
			
	#endregion
	
	#region		COSMALCOS
		var cosmalcosSpells = ds_list_create();
		
		ds_list_add(cosmalcosSpells,
			SPELLS.HOLY_WATER,
			SPELLS.DECAY,
			SPELLS.EXPEL_FORCE,
			SPELLS.SUPERBLOOM,
			SPELLS.LOOMING_DANGER,
			SPELLS.HELLFIRE,
			SPELLS.LORD_MOGRADTHS_RAGE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.DRAIN_LIFEFORCE,
			SPELLS.HIKAMS_WINTER_SPELL,
			SPELLS.AMANDS_ENERGY_BLAST,
			SPELLS.PSYCHIC_IMPACT,
			SPELLS.DESTRUCTIVE_BLOW,
			SPELLS.NOXIOUS_FUMES,
			SPELLS.PSYCHIC_FISSURE,
			SPELLS.DEFLECTIVE_SHIELD,
			SPELLS.DIONS_PARRY,
			SPELLS.DIONS_BARTER_TRICK,
			SPELLS.STINKBOMB,
			SPELLS.CHANNEL_ESSENCE,
			SPELLS.SPHERAS_CURSE,
			SPELLS.TELEKINETIC_BLAST,
			SPELLS.SPHERAS_DEMISE,
			SPELLS.VOLCANIC_ERUPTION,
			SPELLS.ERADICATE,
			SPELLS.DARK_DEAL
		);
	#endregion

#endregion

#region CREATE SPRITE GRID

global.spriteGrid = ds_grid_create(SPRITE_PARAMS.HEIGHT, SPRITES.HEIGHT);

function sprite_add_to_grid(_ID) {
	var i = 0; repeat (SPRITE_PARAMS.HEIGHT) {
		ds_grid_add(global.spriteGrid, i, _ID, argument[i]);
		
		i++;
	}
}

#region ALL SPRITE DATA
//					ID						NAME				SPRITE					ABILITY								ALIGNMENT				USABLE SPELLS						POWER	RES		FIRE	WATER	STORM	EARTH	AGL		LUCK	SIZE
sprite_add_to_grid(SPRITES.HACHACHACHA,		"Hacha-Chacha",		spr_hachaChachaBattle,	ABILITIES.HOT_TO_THE_TOUCH,			ALIGNMENTS.NATURAL,		encode_list(hachaSpells),			80,		50,		170,	50,		75,		110,	90,		150,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.DIIPSY,			"Diipsy",			spr_diipsyBattle,		ABILITIES.WAVY_DANCE,				ALIGNMENTS.NATURAL,		encode_list(diipsySpells),			50,		105,	85,		165,	140,	95,		125,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.GLIDRAKE,		"Glidrake",			spr_glidrakeBattle,		ABILITIES.STORM_SURFER,				ALIGNMENTS.NATURAL,		encode_list(glidrakeSpells),		115,	60,		130,	65,		165,	50,		150,	90,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.PODRIC,			"Podric",			spr_podricBattle,		ABILITIES.NATURES_RECLAMATION,		ALIGNMENTS.NATURAL,		encode_list(podricSpells),			175,	70,		50,		105,	50,		165,	160,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.SPARMATE,		"Sparmate",			spr_sparmateBattle,		ABILITIES.BATTLE_INSTINCT,			ALIGNMENTS.ASTRAL,		encode_list(sparmateSpells),		180,	110,	65,		95,		70,		100,	145,	100,	SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.CRUSTULAR,		"Crustular",		spr_crustularBattle,	ABILITIES.UNBREAKABLE_SHELL,		ALIGNMENTS.NATURAL,		encode_list(crustularSpells),		185,	120,	70,		150,	70,		90,		65,		90,		SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.FISTICOGS,		"Fisticogs",		spr_fisticogsBattle,	ABILITIES.SUPERCHARGED,				ALIGNMENTS.MECHANICAL,	encode_list(fisticogsSpells),		170,	145,	95,		55,		95,		125,	90,		80,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.BOOKISH,			"Bookish",			spr_bookishBattle,		ABILITIES.WELL_READ,				ALIGNMENTS.MECHANICAL,	encode_list(bookishSpells),			50,		45,		120,	120,	135,	120,	95,		90,		SPRITE_SIZES.X_SMALL);
sprite_add_to_grid(SPRITES.PLEEP,			"Pleep",			spr_pleepBattle,		ABILITIES.POWER_OF_FRIENDSHIP,		ALIGNMENTS.ASTRAL,		encode_list(pleepSpells),			130,	65,		115,	70,		155,	50,		115,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.FISHMONGER,		"Fishmonger",		spr_fishmongerBattle,	ABILITIES.UNDERSEA_PREDATOR,		ALIGNMENTS.NATURAL,		encode_list(fishmongerSpells),		165,	130,	60,		165,	90,		80,		95,		80,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.GEMBO,			"Gembo",			spr_gemboBattle,		ABILITIES.UNSTABLE_POWER,			ALIGNMENTS.ASTRAL,		encode_list(gemboSpells),			130,	130,	90,		90,		90,		90,		90,		90,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.JOE,				"Joe",				spr_joeBattle,			ABILITIES.FREE_REFILLS,				ALIGNMENTS.MECHANICAL,	encode_list(joeSpells),				170,	100,	110,	110,	70,		85,		100,	85,		SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.MIRREFRACT,		"Mirrefract",		spr_mirrefractBattle,	ABILITIES.REFLECTIVE_SURFACE,		ALIGNMENTS.MECHANICAL,	encode_list(mirrefractSpells),		150,	85,		80,		50,		120,	90,		110,	85,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.FLOOPWALKER,		"Floopwalker",		spr_floopwalkerBattle,	ABILITIES.FLOWERY_SPIRIT,			ALIGNMENTS.ASTRAL,		encode_list(floopwalkerSpells),		65,		120,	90,		90,		100,	130,	120,	125,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.SONGBIRD,		"Songbird",			spr_songbirdBattle,		ABILITIES.GIFT_OF_SONG,				ALIGNMENTS.ASTRAL,		encode_list(songbirdSpells),		70,		90,		65,		85,		105,	85,		120,	185,	SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.SHREDATOR,		"Shredator",		spr_shredatorBattle,	ABILITIES.HANG_TEN,					ALIGNMENTS.NATURAL,		encode_list(shredatorSpells),		175,	110,	50,		165,	95,		75,		150,	75,		SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.FURVOR,			"Furvor",			spr_furvorBattle,		ABILITIES.TERRITORIAL_HUNTER,		ALIGNMENTS.NATURAL,		encode_list(furvorSpells),			160,	110,	110,	55,		85,		125,	140,	80,		SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.GASTRONIMO,		"Gastronimo",		spr_gastronimoBattle,	ABILITIES.NATURAL_INGREDIENTS,		ALIGNMENTS.MECHANICAL,	encode_list(gastronimoSpells),		140,	140,	100,	100,	70,		100,	60,		100,	SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.DURENDOUX,		"Durendoux",		spr_durendouxBattle,	ABILITIES.ABSORPTIVE_BODY,			ALIGNMENTS.ASTRAL,		encode_list(durendouxSpells),		150,	200,	90,		90,		40,		140,	45,		150,	SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.STAGEFRITE,		"Stagefrite",		spr_stagefriteBattle,	ABILITIES.CREEP_OUT,				ALIGNMENTS.ASTRAL,		encode_list(stagefriteSpells),		60,		75,		55,		55,		55,		55,		110,	150,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.FLAMILIAR,		"Flamiliar",		spr_flamiliarBattle,	ABILITIES.ENDLESS_WICK,				ALIGNMENTS.MECHANICAL,	encode_list(flamiliarSpells),		65,		115,	180,	40,		55,		90,		105,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.SCROOTINEYES,	"Scrootineyes",		spr_scrootineyesBattle,	ABILITIES.ALL_SEEING_EYES,			ALIGNMENTS.NATURAL,		encode_list(scrootineyesSpells),	140,	120,	70,		55,		125,	70,		105,	120,	SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.ARRAYNGE,		"Arraynge",			spr_arrayngeBattle,		ABILITIES.SORT_AWAY,				ALIGNMENTS.MECHANICAL,	encode_list(arrayngeSpells),		45,		65,		120,	70,		150,	70,		145,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.TICKDOFF,		"Tickdoff",			spr_tikdoffBattle,		ABILITIES.SHORT_FUSE,				ALIGNMENTS.MECHANICAL,	encode_list(tikdoffSpells),			130,	75,		190,	50,		110,	60,		120,	85,		SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.FORTUGA,			"Fortuga",			spr_fortugaBattle,		ABILITIES.OFFER_REFUGE,				ALIGNMENTS.NATURAL,		encode_list(fortugaSpells),			90,		190,	65,		155,	75,		135,	45,		100,	SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.SPYOTIS,			"Spyotis",			spr_spyotisBattle,		ABILITIES.SIGNAL_JAMMER,			ALIGNMENTS.MECHANICAL,	encode_list(spyotisSpells),			125,	60,		70,		70,		155,	115,	190,	100,	SPRITE_SIZES.X_SMALL);
sprite_add_to_grid(SPRITES.DRUMLINE,		"Drumline",			spr_drumlineBattle,		ABILITIES.SYNCHRONIZED_SOLDIERS,	ALIGNMENTS.MECHANICAL,	encode_list(drumlineSpells),		100,	130,	80,		80,		80,		120,	140,	150,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.REVOLTURE,		"Revolture",		spr_revoltureBattle,	ABILITIES.HERBAL_CONCOCTION,		ALIGNMENTS.MECHANICAL,	encode_list(revoltureSpells),		105,	140,	75,		70,		85,		80,		85,		75,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.CLEANSAGE,		"Cleansage",		spr_cleansageBattle,	ABILITIES.HEALING_HAZE,				ALIGNMENTS.ASTRAL,		encode_list(cleansageSpells),		70,		125,	135,	60,		105,	140,	55,		80,		SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.FLOTSU,			"Flotsu",			spr_flotsuBattle,		ABILITIES.AQUATIC_ESSENCE,			ALIGNMENTS.NATURAL,		encode_list(flotsuSpells),			90,		135,	50,		180,	100,	85,		60,		100,	SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.HEATSUNE,		"Heatsune",			spr_heatsuneBattle,		ABILITIES.FIERY_AURA,				ALIGNMENTS.ASTRAL,		encode_list(heatsuneSpells),		120,	70,		185,	50,		125,	100,	140,	85,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.BLITZKRANE,		"Blitzkrane",		spr_blitzkraneBattle,	ABILITIES.THUNDROUS_CRY,			ALIGNMENTS.ASTRAL,		encode_list(blitzkraneSpells),		150,	105,	85,		90,		165,	70,		145,	75,		SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.EXONOLITH,		"Exonolith",		spr_exonolithBattle,	ABILITIES.MASSIVE_BODY,				ALIGNMENTS.ASTRAL,		encode_list(exonolithSpells),		70,		210,	90,		60,		90,		140,	50,		100,	SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.PUGILOON,		"Pugiloon",			spr_pugiloonBattle,		ABILITIES.UNDERDOG,					ALIGNMENTS.NATURAL,		encode_list(pugiloonSpells),		145,	80,		90,		100,	115,	75,		155,	80,		SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.MRSUDSY,			"Mr Sudsy",			spr_mrSudsyBattle,		ABILITIES.KEEPING_TIDY,				ALIGNMENTS.MECHANICAL,	encode_list(sudsySpells),			60,		60,		50,		160,	60,		60,		160,	150,	SPRITE_SIZES.X_SMALL);
sprite_add_to_grid(SPRITES.DEMOLITOPS,		"Demolitops",		spr_demolitopsBattle,	ABILITIES.WRECKING_BALL,			ALIGNMENTS.ASTRAL,		encode_list(demolitopsSpells),		180,	110,	160,	75,		60,		110,	90,		100,	SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.DOORMAUS,		"Doormaus",			spr_doormausBattle,		ABILITIES.DRIFT_AWAY,				ALIGNMENTS.ASTRAL,		encode_list(doormausSpells),		50,		65,		95,		95,		110,	95,		185,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.ZEPHIRA,			"Zephira",			spr_zephiraBattle,		ABILITIES.TRICKSTER_FAERIE,			ALIGNMENTS.ASTRAL,		encode_list(zephiraSpells),			85,		60,		55,		65,		145,	105,	175,	100,	SPRITE_SIZES.X_SMALL);
sprite_add_to_grid(SPRITES.CANUKI,			"Canuki",			spr_canukiBattle,		ABILITIES.DUMPSTER_DIVER,			ALIGNMENTS.NATURAL,		encode_list(canukiSpells),			145,	165,	70,		70,		70,		120,	80,		85,		SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.JACKHAMMER,		"Jackhammer",		spr_jackhammerBattle,	ABILITIES.SPRING_LOADED,			ALIGNMENTS.MECHANICAL,	encode_list(jackhammerSpells),		175,	135,	50,		60,		70,		70,		105,	150,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.SPLASHGUARD,		"Splashguard",		spr_splashguardBattle,	ABILITIES.FLOOD_SHELTER,			ALIGNMENTS.NATURAL,		encode_list(splashguardSpells),		60,		60,		50,		165,	110,	95,		125,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.UPROOTER,		"Uprooter",			spr_uprooterBattle,		ABILITIES.PROPOGATE,				ALIGNMENTS.NATURAL,		encode_list(uprooterSpells),		155,	175,	50,		120,	60,		165,	95,		150,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.SNUGBUG,			"Snugbug",			spr_snugbugBattle,		ABILITIES.HEAVY_SLEEPER,			ALIGNMENTS.ASTRAL,		encode_list(snugbugSpells),			55,		55,		75,		75,		75,		95,		160,	100,	SPRITE_SIZES.X_SMALL);
sprite_add_to_grid(SPRITES.PUNKLOPS,		"Punklops",			spr_punklopsBattle,		ABILITIES.GET_ANGRY,				ALIGNMENTS.NATURAL,		encode_list(stinklopsSpells),		150,	110,	105,	70,		125,	95,		60,		35,		SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.PLASMASS,		"Plasmass",			spr_plasmassBattle,		ABILITIES.GENERATOR,				ALIGNMENTS.MECHANICAL,	encode_list(plasmassSpells),		130,	75,		120,	45,		195,	45,		170,	50,		SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.OBSIDUAL,		"Obsidual",			spr_obsidualBattle,		ABILITIES.DUAL_WIELD,				ALIGNMENTS.NATURAL,		encode_list(obsidualSpells),		170,	90,		150,	60,		60,		160,	130,	50,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.NINTOX,			"Nintox",			spr_nintoxBattle,		ABILITIES.SHADOWY_FIEND,			ALIGNMENTS.MECHANICAL,	encode_list(nintoxSpells),			160,	85,		120,	90,		100,	120,	170,	100,	SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.CHROMALIODON,	"Chromosilos",		spr_chromaliodonBattle,	ABILITIES.METAL_MUNCHER,			ALIGNMENTS.MECHANICAL,	encode_list(chromaliodonSpells),	185,	125,	120,	70,		55,		160,	70,		75,		SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.CRAGMA,			"Cragma",			spr_cragmaBattle,		ABILITIES.VOLCANIC_MASS,			ALIGNMENTS.NATURAL,		encode_list(cragmaSpells),			145,	150,	170,	65,		65,		135,	35,		100,	SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.CORVOLT,			"Corvolt",			spr_corvoltBattle,		ABILITIES.EYE_OF_THE_STORM,			ALIGNMENTS.NATURAL,		encode_list(corvoltSpells),			100,	145,	60,		135,	150,	70,		110,	100,	SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.WYRMPOOL,		"Wyrmpool",			spr_wyrmpoolBattle,		ABILITIES.CENTRIPETAL_FORCE,		ALIGNMENTS.ASTRAL,		encode_list(wyrmpoolSpells),		140,	130,	60,		160,	135,	45,		80,		125,	SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.VEWRR,			"Vewrr",			spr_vewrrBattle,		ABILITIES.TEARS_AND_JEERS,			ALIGNMENTS.ASTRAL,		encode_list(vewrrSpells),			150,	115,	105,	80,		90,		95,		45,		85,		SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.DECIDRUID,		"Decidruid",		spr_decidruidBattle,	ABILITIES.PERENNIAL_GROWTH,			ALIGNMENTS.NATURAL,		encode_list(decidruidSpells),		150,	175,	120,	135,	70,		180,	20,		75,		SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.CENOTOMB,		"Cenotomb",			spr_cenotombBattle,		ABILITIES.PURE_MALICE,				ALIGNMENTS.ASTRAL,		encode_list(cenotombSpells),		160,	95,		135,	55,		105,	100,	75,		100,	SPRITE_SIZES.LARGE);
sprite_add_to_grid(SPRITES.STEWARDRAKE,		"Stewardrake",		spr_stewardrakeBattle,	ABILITIES.GUARDIAN_ANGEL,			ALIGNMENTS.ASTRAL,		encode_list(stewardrakeSpells),		80,		155,	120,	90,		135,	90,		115,	100,	SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.HECKID,			"Heckid",			spr_heckidBattle,		ABILITIES.DARK_RITUAL,				ALIGNMENTS.ASTRAL,		encode_list(heckidSpells),			70,		60,		125,	50,		140,	125,	105,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.DOMINO,			"Domino",			spr_dominoBattle,		ABILITIES.RING_LEADER,				ALIGNMENTS.MECHANICAL,	encode_list(dominoSpells),			135,	50,		65,		65,		65,		65,		140,	150,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.ANACHRONAUT,		"Anachronaut",		spr_anachronautBattle,	ABILITIES.TIME_POLICE,				ALIGNMENTS.MECHANICAL,	encode_list(anachronautSpells),		50,		55,		120,	120,	120,	120,	170,	100,	SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.SHPUPO,			"Shpupo",			spr_shpupoBattle,		ABILITIES.SPACE_CADET,				ALIGNMENTS.ASTRAL,		encode_list(shpupoSpells),			120,	80,		80,		125,	100,	100,	175,	60,		SPRITE_SIZES.MEDIUM);
sprite_add_to_grid(SPRITES.NEEDLEPAW,		"Needlepaw",		spr_needlepawBattle,	ABILITIES.BAD_OMEN,					ALIGNMENTS.ASTRAL,		encode_list(needlepawSpells),		155,	55,		110,	50,		90,		110,	180,	50,		SPRITE_SIZES.SMALL);
sprite_add_to_grid(SPRITES.OMNOST,			"Omnost",			spr_omnostBattle,		ABILITIES.ALL_KNOWING,				ALIGNMENTS.ASTRAL,		encode_list(omnostSpells),			50,		80,		110,	110,	150,	110,	70,		150,	SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.PRISMATTER,		"Prismatter",		spr_prismatterBattle,	ABILITIES.BEND_PHYSICS,				ALIGNMENTS.NATURAL,		encode_list(prismatterSpells),		180,	145,	40,		135,	40,		135,	75,		35,		SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.KRONARC,			"Kronarc",			spr_kronarcBattle,		ABILITIES.COMPRESS_TIME,			ALIGNMENTS.MECHANICAL,	encode_list(kronarcSpells),			80,		120,	120,	120,	120,	120,	115,	150,	SPRITE_SIZES.X_LARGE);
sprite_add_to_grid(SPRITES.COSMALCOS,		"Cosmalcos",		spr_cosmalcosBattle,	ABILITIES.END_OF_DAYS,				ALIGNMENTS.NATURAL,		encode_list(cosmalcosSpells),		120,	195,	50,		50,		50,		50,		30,		150,	SPRITE_SIZES.X_LARGE);

#endregion

// encode grid
global.allSprites = encode_grid(global.spriteGrid);

// delete grid

#endregion

function sprite_get_stat(_stat, _sprite) {
	var sp	= _sprite;
	var st	= _stat;
	var g	= global.spriteGrid;
	
	var val	= g[# st,	sp];
	return val;
}

function sprite_load_parameters() {
	// decode sprite grid
	var grid = ds_grid_create(SPRITE_PARAMS.HEIGHT, SPRITES.HEIGHT);
	decode_grid(global.allSprites, grid);
	
	// use sprite grid to get parameters
	name				= grid[# SPRITE_PARAMS.NAME,			spriteID];
	sprite				= real(grid[# SPRITE_PARAMS.SPRITE,		spriteID]);
	baseAlign			= real(grid[# SPRITE_PARAMS.ALIGNMENT,	spriteID]);
	var spellString		= grid[# SPRITE_PARAMS.SPELL_LIST,		spriteID];
	basePower			= real(grid[# SPRITE_PARAMS.POWER,		spriteID]);
	baseResistance		= real(grid[# SPRITE_PARAMS.RESISTANCE,	spriteID]);
	baseFire			= real(grid[# SPRITE_PARAMS.FIRE,		spriteID]);
	baseWater			= real(grid[# SPRITE_PARAMS.WATER,		spriteID]);
	baseStorm			= real(grid[# SPRITE_PARAMS.STORM,		spriteID]);
	baseEarth			= real(grid[# SPRITE_PARAMS.EARTH,		spriteID]);
	baseAgility			= real(grid[# SPRITE_PARAMS.AGILITY,	spriteID]);
	baseLuck			= real(grid[# SPRITE_PARAMS.LUCK,		spriteID]);
	baseSize			= real(grid[# SPRITE_PARAMS.SIZE,		spriteID]);
	
	baseAbility			= real(grid[# SPRITE_PARAMS.ABILITY,	spriteID]);
	
	// decode ability grid
	var abltGrid = ds_grid_create(ABILITY_PARAMS.HEIGHT, ABILITIES.HEIGHT);
	decode_grid(global.allAbilities, abltGrid);
	
	baseAbilityType		= real(abltGrid[# ABILITY_PARAMS.TYPE,				baseAbility]);
	baseAbilityName		= abltGrid[# ABILITY_PARAMS.NAME,					baseAbility];
	baseAbilityDesc		= abltGrid[# ABILITY_PARAMS.DESCRIPTION,			baseAbility];
	baseAbilityFunction = real(abltGrid[# ABILITY_PARAMS.EFFECT_FUNCTION,	baseAbility]);
	
	// set all current stats
	currentPower			= basePower;
	currentResistance		= baseResistance;
	currentAgility			= baseAgility;
	currentLuck				= baseLuck;
	currentFire				= baseFire;
	currentWater			= baseWater;
	currentStorm			= baseStorm;
	currentEarth			= baseEarth;
	currentSize				= baseSize;
	currentAlign			= baseAlign;
	currentAbility			= baseAbility;
	currentAbilityType		= baseAbilityType;
	currentAbilityName		= baseAbilityName;
	currentAbilityDesc		= baseAbilityDesc;
	currentAbilityFunction	= baseAbilityFunction;	
	
	// decode spell list
	decode_list(spellString, usableSpells);
	
	// delete sprite grid and ability grid
	ds_grid_destroy(grid);
	ds_grid_destroy(abltGrid);
}

function sprite_get_alignment_string(_alignment) {
	var a = _alignment;
	
	switch (a) {
		case ALIGNMENTS.ASTRAL:		return "ASTRAL";
		case ALIGNMENTS.MECHANICAL:	return "MECHANICAL";
		case ALIGNMENTS.NATURAL:	return "NATURAL";
	}
	
	return "???";
}

function sprite_get_size_string(_size) {
	var s = _size;
	
	switch (s) {
		case SPRITE_SIZES.X_SMALL:		return "X-SMALL";
		case SPRITE_SIZES.SMALL:		return "SMALL";
		case SPRITE_SIZES.MEDIUM:		return "MEDIUM";
		case SPRITE_SIZES.LARGE:		return "LARGE";
		case SPRITE_SIZES.X_LARGE:		return "X-LARGE";
	}
}

function teambuilder_get_sprite_parameters() {
	var sid = -1;
	
	if (talismanList[| selectedNameSlot] != "-1") {
		sid = talismanList[| selectedNameSlot];	
	}

	currentSprite		= spriteGrid[# SPRITE_PARAMS.SPRITE,		sid];
	currentFire			= spriteGrid[# SPRITE_PARAMS.FIRE,			sid];
	currentWater		= spriteGrid[# SPRITE_PARAMS.WATER,			sid];
	currentStorm		= spriteGrid[# SPRITE_PARAMS.STORM,			sid];
	currentEarth		= spriteGrid[# SPRITE_PARAMS.EARTH,			sid];
	currentAgility		= spriteGrid[# SPRITE_PARAMS.AGILITY,		sid];
	currentAlign		= spriteGrid[# SPRITE_PARAMS.ALIGNMENT,		sid];
	currentSize			= spriteGrid[# SPRITE_PARAMS.SIZE,			sid];
	currentAbility		= spriteGrid[# SPRITE_PARAMS.ABILITY,		sid];
	currentPower		= spriteGrid[# SPRITE_PARAMS.POWER,			sid];
	currentResistance	= spriteGrid[# SPRITE_PARAMS.RESISTANCE,	sid];
	currentLuck			= spriteGrid[# SPRITE_PARAMS.LUCK,			sid];
	
	var abltGrid = ds_grid_create(ABILITY_PARAMS.HEIGHT, ABILITIES.HEIGHT);
	decode_grid(global.allAbilities, abltGrid);
	
	currentAbilityDesc	= abltGrid[# ABILITY_PARAMS.DESCRIPTION,	currentAbility];
	currentAbilityName	= abltGrid[# ABILITY_PARAMS.NAME,			currentAbility];
	
	ds_grid_destroy(abltGrid);
}